name: AriseMC-PvP
version: 1.0.0
author: TeamHardcore
main: de.teamhardcore.pvp.Main

depend:
  - ProtocolLib
  - WorldGuard
  - WorldEdit

commands:
  fix:
  stack:
  tpa:
    aliases:
      - tpahere
      - tpaall
      - tpaccept
      - tpdeny
  tpall:
  tphere:
  tptop:
  warp:
    aliases:
      - warps
  spawn:
    aliases:
      - setspawn
  support:
  back:
  workbench:
    aliases:
      - wb
      - werkbank
  playertime:
    aliases:
      - ptime
  feed:
    aliases:
      - eat
      - essen
  heal:
  near:
  enderchest:
    aliases:
      - ec
      - e
  hat:
  vanish:
  bodysee:
  report:
  money:
    aliases:
      - geld
      - pay
  globalmute:
  fill:
  broadcast:
    aliases:
      - bc
  msg:
    aliases:
      - tell
      - whisper
      - t
      - m
      - pn
      - r
      - reply
      - antworten
      - w
  trash:
  clan:
    aliases:
      - c
  fly:
  spawner:
  extras:
  ban:
  mute:
  debug:
  kit:
  markt:
    aliases:
      - verkaufen
  more:
  duel:
    aliases:
      - duell
  invsee:
  home:
    aliases:
      - homes
      - sethome
      - delhome
  kick:
    aliases:
      - kickall
  commandspy:
  achievements:
    aliases:
      - achievement
  rename:
  relore: